name: Project Testing and Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.2"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up ZenML
        run: |
          zenml integration install mlflow evidently --yes
          zenml integration install airflow --yes


      - name: Run Ruff on pipelines and steps
        run: ruff check pipelines steps
        continue-on-error: true
        env:
          RUFF_FORMAT: github

      - name: Run pytest on tests directory
        run: PYTHONPATH=$(pwd) pytest tests