name: Project Testing and Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.2"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up ZenML
        run: |
          zenml integration install mlflow evidently --yes
          zenml integration install airflow --yes


      - name: Run Ruff on pipelines and steps
        run: ruff check pipelines steps
        continue-on-error: true
        env:
          RUFF_FORMAT: github

      - name: Run pytest on tests directory
        run: PYTHONPATH=$(pwd) pytest tests

      - name: Set up README.md with Hugging Face Spaces config
        run: |
          cat <<EOF > app/README.md
          ---
          title: Salary Predictor
          emoji: 💼
          colorFrom: blue
          colorTo: green
          sdk: gradio
          sdk_version: "5.36.2"
          app_file: app.py
          pinned: false
          ---

          A simple salary prediction app using a linear regression model.
          EOF
        

      - name: Push app folder to Hugging Face Spaces repo
        env:
          DTCTOKEN: ${{ secrets.DTCTOKEN }}
        run: |
          git config --global user.email "olufemig@outlook.com"
          git config --global user.name "olufemig"

          cd app
          git init --initial-branch=main
          git remote add origin https://olufemig:${DTCTOKEN}@huggingface.co/spaces/olufemig/salarypredictor
          git add model.pkl app.py requirements.txt  # Include your app files here
          git commit -m "Update model and app"
          git push --force origin main
